#!/bin/sh

set -o nounset -o errexit #-o pipefail - only in bash

INPUT_INDEX_HTML_TEMPLATE=${INPUT_INDEX_HTML_TEMPLATE:-'./index.html'}
OUTPUT_INDEX_HTML=${OUTPUT_INDEX_HTML:-''}
RESOURCE_FOLDER=${RESOURCE_FOLDER:-'.'}

export TITLE=${TITLE:-'Continuous Delivery Slides'}
export THEME_CSS=${THEME_CSS:-'css/cloudogu.css'}
export ADDITIONAL_DEPENDENCIES=${ADDITIONAL_DEPENDENCIES:-''}

BASEDIR=$(dirname $0)     
ABSOLUTE_BASEDIR="$( cd $BASEDIR && pwd )"

if [ -f "${RESOURCE_FOLDER}/footer.html" ]; then
    export FOOTER_HTML="<div class=\"footer text-smaller state-background\">$(cat "${RESOURCE_FOLDER}/footer.html")
</div>"
fi

if [ -f "${RESOURCE_FOLDER}/body-end.html" ]; then
    export BODY_END_HTML="$(cat "${RESOURCE_FOLDER}/body-end.html")"
fi

if [ -f "${RESOURCE_FOLDER}/slides.html" ]; then
    export SLIDES_HTML="$(cat "${RESOURCE_FOLDER}/slides.html")"
else
    # TODO parse all .md files from docs/slides 
    echo "WARNING: No slides.html found in ${RESOURCE_FOLDER}. Using default presentation."
    export SLIDES_HTML="$(cat "${ABSOLUTE_BASEDIR}/default-slides.html")"
fi

if [ -f "${RESOURCE_FOLDER}/additional.js" ]; then
    export ADDITIONAL_SCRIPT="<script>
    $(cat "${RESOURCE_FOLDER}/additional.js")
</script>"
fi 

TMP_FILE="$(mktemp)"

envsubst < "${INPUT_INDEX_HTML_TEMPLATE}" > "${TMP_FILE}"

if [ -n "${OUTPUT_INDEX_HTML}" ]; then
    mv "${TMP_FILE}" "${OUTPUT_INDEX_HTML}"
else 
   cat "${TMP_FILE}"
fi

rm -f "${TMP_FILE}"
