#!/bin/sh

set -o nounset -o errexit #-o pipefail - only in bash

WEB_FOLDER="${WEB_FOLDER:-"/reveal"}"
INPUT_INDEX_HTML_TEMPLATE="${INPUT_INDEX_HTML_TEMPLATE:-"${WEB_FOLDER}/index.html"}"
OUTPUT_INDEX_HTML="${OUTPUT_INDEX_HTML:-"${WEB_FOLDER}/index.html"}"
CAT_INDEX_HTML="${CAT_INDEX_HTML:-""}"
RESOURCE_FOLDER="${RESOURCE_FOLDER:-"/resources"}"
SLIDES_FOLDER="docs/slides"

export TITLE=${TITLE:-'Continuous Delivery Slides'}
export THEME_CSS=${THEME_CSS:-'css/cloudogu.css'}
export ADDITIONAL_DEPENDENCIES=${ADDITIONAL_DEPENDENCIES:-''}
export ADDITIONAL_REVEAL_OPTIONS=${ADDITIONAL_REVEAL_OPTIONS:-''}
export SHOW_NOTES_FOR_PRINTING=${SHOW_NOTES_FOR_PRINTING:-'false'}

BASEDIR=$(dirname $0)     
ABSOLUTE_BASEDIR="$( cd $BASEDIR && pwd )"

if [ -f "${RESOURCE_FOLDER}/footer.html" ]; then
    export FOOTER_HTML="<div class=\"footer text-smaller state-background\">$(cat "${RESOURCE_FOLDER}/footer.html")
</div>"
fi

if [ -f "${RESOURCE_FOLDER}/body-end.html" ]; then
    export BODY_END_HTML="$(cat "${RESOURCE_FOLDER}/body-end.html")"
fi

if [ -f "${RESOURCE_FOLDER}/slides.html" ]; then
    export SLIDES_HTML="$(cat "${RESOURCE_FOLDER}/slides.html")"
else
    echo "No slides.html found in ${RESOURCE_FOLDER}. Serving all files from ${SLIDES_FOLDER} as markdown:"
    find "${WEB_FOLDER}/${SLIDES_FOLDER}" -type f -exec basename '{}' \;  | sort
    
    export SLIDES_HTML="$(cd "${WEB_FOLDER}" && \
                          find "${SLIDES_FOLDER}" -type f -print0 | \
                          sort -z | \
                          xargs -r0 -I '{}' \
                            echo  "<section data-markdown=\"{}\" data-separator-vertical=\"^\r?\n\r?\n\r?\n\"></section>" \
                         )"
fi

if [ -f "${RESOURCE_FOLDER}/additional.js" ]; then
    export ADDITIONAL_SCRIPT="<script>
    $(cat "${RESOURCE_FOLDER}/additional.js")
</script>"
fi 

TMP_FILE="$(mktemp)"

envsubst < "${INPUT_INDEX_HTML_TEMPLATE}" > "${TMP_FILE}"

if [ -n "${CAT_INDEX_HTML}" ]; then
   cat "${TMP_FILE}"
else 
   mv "${TMP_FILE}" "${OUTPUT_INDEX_HTML}"
fi

# Make world readable to allow reading even when container is run with arbitrary ID
chmod o+r "${OUTPUT_INDEX_HTML}"

rm -f "${TMP_FILE}"
